### ISSUE TITLE
Remove the leading 0 in refresh timer

### ISSUE THREAD

**Issue by stuntguy3000** [SteamDatabase/steamstat.us#11]
Explicitly coded into the update timer is this leading 0.
https://github.com/SteamDatabase/steamstat.us/blob/9d22bcb87f23233663993cb4c4315489113633e8/static/app.js#L60

I believe it looks slightly better to leave this out [ignore colour difference] as this has a more natural feel to it.
![image](https://user-images.githubusercontent.com/1522389/55453552-e954be80-5623-11e9-8aac-46822174da3d.png)

Where as how it currently is does not convey this feeling
![image](https://user-images.githubusercontent.com/1522389/55453591-08ebe700-5624-11e9-8049-3dc33c6db445.png)

**Comment by yaakov-h** [comment]
Having the leading zero keeps "seconds" in the same place and prevents it bouncing horizontally as time elapses.

**Comment by stuntguy3000** [comment]
In my opinion 0X number looks weirder than a number you would expect to
move as it gets smaller
