### ISSUE TITLE
Guangzhou & Tianjin CM

### ISSUE THREAD

**Issue by wordlesswind** [SteamDatabase/steamstat.us#12]
Hello, Pavel.

Guangzhou CM is `can` & `pwg`
Tianjin CM is `tsn` & `pwj`

`pw*`: Its actual use is unknown.
It was once available for the worldwide server, but was not available after an update.
And I have never used these in actual use(auto). After `sdr` was deleted, I couldn't force it.

And `pwu` is Shijiazhuang; `pww` & `wuh` is Wuhan; `pwz` is Jiaxing.

Maybe only players in nearby areas will use these SDR servers

The only thing I can confirm is that `sha`, `can` and `tsn` are dedicated to perfectworld servers.

**Comment by xPaw** [comment]
Guangzhou and Tianjin in the list comes from CS:GO server status, it's not the CM.

I'm not sure why you think it's two pops at once, you think they combine two into one?

**Comment by wordlesswind** [comment]
Maybe something is wrong with my understanding.
I just want to say if you can add a code.
Because their codename is can and tsn
Sorry :(

**Comment by wordlesswind** [comment]
And `cant` and `pwg` have the same IP address range.

https://github.com/SteamDatabase/GameTracking-CSGO/blob/888132b9c8b33be835b9b7567c07f35ce3e9949b/platform/config/network_config.json#L787-L817
https://github.com/SteamDatabase/GameTracking-CSGO/blob/888132b9c8b33be835b9b7567c07f35ce3e9949b/platform/config/network_config.json#L142-L178

So I thought they were in the same computer room. Just the functions are different.

![cant](https://user-images.githubusercontent.com/9050713/73667198-e365b900-46de-11ea-83cf-fdc7988c8e0c.PNG)
![pwg](https://user-images.githubusercontent.com/9050713/73667200-e3fe4f80-46de-11ea-8dc0-614b9139b5f2.PNG)
But I traced the route and found that it might not be in the same computer room.
In any case, they are sure to be in Guangzhou.

The thing I can be sure of is that the data center must be `sha`, `can` and `tsn`.
`pw*` are just SDR servers.
