### ISSUE TITLE
SteamChina CM

### ISSUE THREAD

**Issue by wordlesswind** [SteamDatabase/steamstat.us#13]
Hello, xPaw

When I use `-dev -steamchina` to access SteamChina, I found that the CM address for SteamChina appears in config.vdf.

```
cm1-sha1.cm.wmsjsteam.com:443
cm1-sha1.cm.wmsjsteam.com:27020
cm1-sha1.cm.wmsjsteam.com:27021
cm1-sha1.cm.wmsjsteam.com:27022
```

I checked the IP, it is completely different from `CM<_01-06_>-SHA.cm.steampowered.com`.
The server of `cm1-sha1.cm.wmsjsteam.com` is located in Shanghai, and the server of `CM<_01-06 _>-SHA.cm.steampowered.com` is located in Wuxi, Jiangsu Province.

I want to know which CM is Shanghai on Steam Status?
Then can you add another one that is not added? After all, they are different.
I researched it, but unfortunately I do n’t know how to use https://api.steampowered.com/ISteamDirectory/GetCMList/v1

Thanks!

**Comment by xPaw** [comment]
`cm1-sha1.cm.wmsjsteam.com` resolves to the same IP as `cm1-sha1.cm.steampowered.com`.

Steamstatus shows the CMs returned by the APIs.

**Comment by wordlesswind** [comment]
OK, I found APIs.

https://api.steampowered.com/ISteamDirectory/GetCMList/v0001/?cellid=0&format=vdf&launcher=7&steamrealm=steamchina

http://api.steampowered.com/ISteamDirectory/GetCMList/v0001/?cellid=0&format=vdf&launcher=0&steamrealm=steamglobal

**Comment by wordlesswind** [comment]
Hi @xPaw ,

Is this useful?
Because `CM <_01-06 _>-SHA.cm.steampowered.com` is different from `cm1-sha1.cm.wmsjsteam.com`.
`cm1-sha1.cm.wmsjsteam.com` is dedicated to SteamChina.
