### ISSUE TITLE
SteamChina/Perfect World CS:GO & DOTA 2 Connection Managers

### ISSUE THREAD

**Issue by wordlesswind** [SteamDatabase/steamstat.us#14]
![215218npnff19081pzqqq0](https://user-images.githubusercontent.com/9050713/84404603-a3d54d80-ac39-11ea-9b6b-a8026837569d.png)
I discovered through Fiddler that the Perfect World CS:GO launcher is already based on SteamChina rather than Steam. 

(There is also evidence that on May 30th, when playing Perfect World CS:GO on Steam, there will be a problem that it is incorrectly included in the anti-addiction system, and the CS:GO launcher is not affected. https://www.weibo.com/5980136393/J4uYow31S)

https://api.steampowered.com/ISteamDirectory/GetCMList/v0001/?cellid=0&format=vdf&launcher=4&steamrealm=steamchina

Since the three CS:GO data centers in Mainland China are all servers dedicated to Perfect World CS:GO, I suggest adding SteamChina’s CM to Steam Status. Because It is already in use.

The CellID of "China - Shanghai" is 47.
https://api.steampowered.com/ISteamDirectory/GetCMList/v1/?cellid=47&steamrealm=steamchina

**Comment by xPaw** [comment]
The `wmsjsteam.com` addresses you are seeing resolve to the same IP as `steampowered.com`, so it is already covered by "Shanghai" on steamstat.us

$ nslookup cm2-sha1.cm.wmsjsteam.com
Address: 114.141.134.189

$ nslookup cm2-sha1.cm.steampowered.com
Address: 114.141.134.189

**Comment by wordlesswind** [comment]
> The `wmsjsteam.com` addresses you are seeing resolve to the same IP as `steampowered.com`, so it is already covered by "Shanghai" on steamstat.us
> 
> $ nslookup cm2-sha1.cm.wmsjsteam.com
> Address: 114.141.134.189
> 
> $ nslookup cm2-sha1.cm.steampowered.com
> Address: 114.141.134.189

I know what you mean.  But in addition to `cm2-sha1` and `cm1-sha1` for SteamChina, there is also `CM<01-06>-SHA` that was originally used for SteamGlobal.

Considering that SteamChina may be independent of SteamGlobal, I wonder if Steam China services should be distinguished from SteamGlobal?

In other words, don't use SteamChina's Shanghai CM to overwrite SteamGlobal's Shanghai CM, but add new items.

**Comment by xPaw** [comment]
Will see how it goes in the future, for now these PW servers are grouped into Shanghai.
