### ISSUE TITLE
CS servers in Chengdu, China

### ISSUE THREAD

**Issue by cherinyy** [SteamDatabase/steamstat.us#19]
![image](https://github.com/SteamDatabase/steamstat.us/assets/9050713/13668efc-cf16-44f9-912b-60aba3e3d50e)

https://github.com/SteamDatabase/GameTracking-CS2/commit/e13577bb6387af1062e2fa84c2a26f35aa5029e7#diff-5a92baa87a9b95661bda6e243288baa4a150cbcf6110cc8cd26219bad4b47250R33088

Oh, not in the API data, waiting for an Valve update......

**Comment by xPaw** [comment]
They're added when they're available.
