### ISSUE TITLE
Add tsn CS:GO MM Servers

### ISSUE THREAD

**Issue by 872517414** [SteamDatabase/steamstat.us#6]
![3](https://cloud.githubusercontent.com/assets/9050713/22111265/b0627710-de99-11e6-9d4b-6a5562d0dfa6.png)
![1](https://cloud.githubusercontent.com/assets/9050713/22111275/bebd744a-de99-11e6-86ed-0474e48dec8c.jpg)

**Comment by garciabruno** [comment]
Do you know if people in China can access steamstat.us?

**Comment by 872517414** [comment]
@garciabruno
Yep,we can. Although China Mobile(Chinese ISP) blocked Cloudflare,the GFW(China National Firewall) isn't.
Because in China,Baidu and Cloudflare to reach cooperation([Baidu CDN](https://su.baidu.com)).

**Comment by nicedayzhu** [comment]
finally it comes to china to have its own mm server. Let' go tsn server! Add this pls!

**Comment by xPaw** [comment]
It will be added when it's reported in Valve's `GetGameServersStatus` API.
