### ISSUE TITLE
Make Steam WebSocket CMs times the same as the client timezone and add support for localization

### ISSUE THREAD

**Issue by guiscaranse** [SteamDatabase/steamstat.us#7]
I live in Brazil, and I realized that the dates which are shown under Steam WebSocket CMs graphics does not match with my computer clock. I am not sure tho which timezone the steamstatus is configured by default.
It would be nice to make the dates and time the same as the client timezone.

Also, adding support for localization would be amazing, since there aren't a lot of strings to translate.

**Comment by xPaw** [comment]
I've changed the graph to use local time, and I have no plans on adding localization.
