### ISSUE TITLE
Can I set up a mirror website in China?

### ISSUE THREAD

**Issue by wordlesswind** [SteamDatabase/steamstat.us#8]
CLOUDFLARE Free Plan is not friendly to China Network.
There is now a service similar to GitHub Pages in China, [Coding Pages](https://coding.net/v1/pages/).
Their server is deployed in Hong Kong.
Maybe you can sign up for an account? But it does not seem to be in English.

**Comment by wordlesswind** [comment]
@xPaw 
![1](https://user-images.githubusercontent.com/9050713/39186672-c8ac9ef8-47fd-11e8-89ab-8784d776a16d.png)

**Comment by xPaw** [comment]
And what's the response body?

**Comment by wordlesswind** [comment]
@xPaw 
![view-source_https___crowbar steamstat us](https://user-images.githubusercontent.com/9050713/39187193-323e2340-47ff-11e8-9281-92e15f70dccd.png)

**Comment by xPaw** [comment]
Go to steamstat.us and save HAR file in devtools. In network tab, right click and select `Save as HAR with Content`. And send me that file.

https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting

**Comment by wordlesswind** [comment]
@xPaw 
[steamstat.us.har.zip](https://github.com/SteamDatabase/steamstat.us/files/1942774/steamstat.us.har.zip)

**Comment by xPaw** [comment]
All the content loads just fine from the server. Do you have any errors in console? Try without extensions or in another browser.

**Comment by wordlesswind** [comment]
it's fine, butit's too slow...
